POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
	"title": "Title 2",
	"author": "Vitor",
	"url": "https://google.com/",
	"likes": 1,
	"userId": "5fa4376809a8d559202f6dad"
}

